common/models/Mainpage.php
<?php

namespace common\models;

use Yii;
use \common\models\base\Mainpage as BaseMainpage;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "mainpage".
 */
class Mainpage extends BaseMainpage
{

public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                # custom behaviors
            ]
        );
    }

    public function rules()
    {
        return [
            [['name', 'en_name', 'phone', 'email', 'address', 'en_address', 'advantages', 'en_advantages', 'rules', 'en_rules', 'about', 'en_about'], 'required'],
            [['advantages', 'en_advantages', 'rules', 'en_rules', 'about', 'en_about'], 'string'],
            [['name', 'en_name', 'seo_description', 'advantages', 'en_advantages', 'rules', 'en_rules', 'about', 'en_about'], 'string'],
            [['seo_title', 'en_seo_title'], 'string', 'max' => 80],
            [['seo_description', 'en_seo_description'], 'string', 'max' => 150],
        ];
    }
    public function getLang_seo_h1() {
        if (Yii::$app->language == 'en') {
            return $this->en_seo_h1;
        } else {
            return $this->seo_h1;
        }
    }

    public function getLang_seo_title() {
        if (Yii::$app->language == 'en') {
            return $this->en_seo_title;
        } else {
            return $this->seo_title;
        }
    }

    public function getLang_seo_description() {
        if (Yii::$app->language == 'en') {
            return $this->en_seo_description;
        } else {
            return $this->seo_description;
        }
    }

    public function getLang_seo_keywords() {
        if (Yii::$app->language == 'en') {
            return $this->en_seo_keywords;
        } else {
            return $this->seo_keywords;
        }
    }

    public function getLang_name() {
        if (Yii::$app->language == 'en') {
            return $this->en_name;
        } else {
            return $this->name;
        }
    }

    public function getLang_advantages() {
        if (Yii::$app->language == 'en') {
            return $this->en_advantages;
        } else {
            return $this->advantages;
        }
    }

    public function getLang_rules() {
        if (Yii::$app->language == 'en') {
            return $this->en_rules;
        } else {
            return $this->rules;
        }
    }

    public function getLang_about() {
        if (Yii::$app->language == 'en') {
            return $this->en_about;
        } else {
            return $this->about;
        }
    }

    public function getLang_address() {
        if (Yii::$app->language == 'en') {
            return $this->en_address;
        } else {
            return $this->address;
        }
    }
}

common/models/Textpage.php
<?php

namespace common\models;

use himiklab\sortablegrid\SortableGridBehavior;
use Yii;
use \common\models\base\Textpage as BaseTextpage;
use yii\behaviors\SluggableBehavior;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/**
 * This is the model class for table "textpage".
 */
class Textpage extends BaseTextpage
{

    public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                [
                    'class' => SluggableBehavior::className(),
                    'attribute' => 'name',
                    'slugAttribute' => 'alias',
                    'immutable' => true,
                    'ensureUnique' => true,
                ],
                'sort' => [
                    'class' => SortableGridBehavior::className(),
                    'sortableAttribute' => 'sortOrder'
                ],
            ]
        );
    }

    public function rules()
    {
        return [
            [['name', 'en_name'], 'required'],
            [['html', 'en_html', 'anons', 'en_anons', 'table', 'en_table'], 'string'],
            [['parent_id', 'sortOrder'], 'integer'],
            [['image'], 'safe'],
            [['name', 'en_name', 'alias', 'seo_keywords', 'en_seo_keywords', 'seo_h1', 'en_seo_h1'], 'string', 'max' => 255],
            [['seo_title', 'en_seo_title'], 'string', 'max' => 80],
            [['seo_description', 'en_seo_description'], 'string', 'max' => 150],
        ];
    }

    public static function getTextpages($id = NULL) {
        $textpages = Textpage::find()->where([])->all();
        $result = [];
        $result[0] = 'Нет родителя';

        if ($id == NULL) {
            foreach($textpages as $p) {
                $result[$p['id']] = $p['name'];
            }
        } else {
            foreach($textpages as $p) {
                if ($id != $p['id'])
                    $result[$p['id']] = $p['name'];
            }
        }

        return $result;
    }

    public function getLang_name() {
        if (Yii::$app->language == 'en') {
            return $this->en_name;
        } else {
            return $this->name;
        }
    }

    public function getUrl() {
        if ($this->parent_id == 1) {
            return Url::to(['site/index', 'alias' => Textpage::findOne(1)->alias, 'alias2' => $this->alias]);
        } else {
            return Url::to(['site/index', 'alias' => $this->alias]);
        }
    }

    public function liLink() {
        $url = $this->url;

        if ($_SERVER['REQUEST_URI'] == $url) {
            return '<li class="active"><span>'.$this->lang_name.'</span></li>';
        } else {
            return '<li><a href="'.$url.'">'.$this->lang_name.'</a></li>';
        }
    }
    public function getLang_seo_h1() {
        if (Yii::$app->language == 'en') {
            return $this->en_seo_h1;
        } else {
            return $this->seo_h1;
        }
    }

    public function getLang_seo_title() {
        if (Yii::$app->language == 'en') {
            return $this->en_seo_title;
        } else {
            return $this->seo_title;
        }
    }

    public function getLang_seo_description() {
        if (Yii::$app->language == 'en') {
            return $this->en_seo_description;
        } else {
            return $this->seo_description;
        }
    }

    public function getLang_seo_keywords() {
        if (Yii::$app->language == 'en') {
            return $this->en_seo_keywords;
        } else {
            return $this->seo_keywords;
        }
    }

    public function getLang_html() {
        if (Yii::$app->language == 'en') {
            return $this->en_html;
        } else {
            return $this->html;
        }
    }

    public function getLang_anons() {
        if (Yii::$app->language == 'en') {
            return $this->en_anons;
        } else {
            return $this->anons;
        }
    }

    public function getLang_table() {
        if (Yii::$app->language == 'en') {
            return $this->en_table;
        } else {
            return $this->table;
        }
    }
}

backend/controllers/TextpageController.php
<?php

namespace backend\controllers;

use backend\models\UploadFile;
use common\models\Textpage;
use himiklab\sortablegrid\SortableGridAction;

/**
* This is the class for controller "TextpageController".
*/
class TextpageController extends \backend\controllers\base\TextpageController
{
    public function actions()
    {
        return [
            'sort' => [
                'class' => SortableGridAction::className(),
                'modelName' => Textpage::className(),
            ],
        ];
    }

    public function actionCreate()
    {
        $model = new Textpage;

        try {
            if ($model->load($_POST)) {
                $model->image = UploadFile::upload($model, 'image', 'image', []);

                if ($model->save()) {
                    return $this->redirect(['index']);
                }
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $image = $model->image;

        if ($model->load($_POST)) {
            if (!empty($_FILES['Textpage']['name']['image'])) {
                $model->image = UploadFile::upload($model, 'image', 'image', []);
            } else {
                $model->image = $image;
            }

            if ($model->save()) {
                return $this->redirect(['index']);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
}

frontend/views/textpage/contacts.php
<?php

use common\models\Textpage;
use yii\helpers\Url;

$this->params['seo_title'] = $model->lang_seo_title;
$this->params['seo_description'] = $model->lang_seo_description;
$this->params['seo_keywords'] = $model->lang_seo_keywords;
$this->params['name'] = $model->lang_name;

?>

<!--main-content-->
<div class="main-content">
    <section class="title-section">
        <div class="container">
            <div class="title-content">
                <ul class="breadcrumbs">
                    <li><span><?=$model->lang_name?></span></li>
                </ul>
                <h1><?=(!empty($model->lang_seo_h1)) ? $model->lang_seo_h1 : $model->lang_name?></h1>
            </div>
        </div>
    </section>

    <?=$this->render('@frontend/views/blocks/contacts')?>
</div>
<!--//main-content-->

frontend/views/textpage/index.php
<?php

use common\models\Mainpage;
use common\models\Textpage;
use yii\helpers\Url;

$this->params['seo_title'] = $model->lang_seo_title;
$this->params['seo_description'] = $model->lang_seo_description;
$this->params['seo_keywords'] = $model->lang_seo_keywords;
$this->params['name'] = $model->lang_name;

$mainPage = Mainpage::findOne(1);

?>

<!--main-content-->
<div class="main-content">
    <section class="order-title-section">
        <?=$this->render('@frontend/views/blocks/bron', ['model' => $model])?>
        <div class="container">
            <ul class="breadcrumbs">
                <li><span><?=$model->lang_name?></span></li>
            </ul>
            <h1><?=(!empty($model->lang_seo_h1)) ? $model->lang_seo_h1 : $model->lang_name?></h1>
            <div class="year-price">
                <?=$model->lang_anons?>
            </div>
        </div>
    </section>

    <div class="container">
        <?=$model->lang_html?>
    </div>
</div>
<!--//main-content-->

frontend/views/textpage/udobstva.php
<?php

use common\models\Mainpage;
use common\models\Textpage;
use yii\helpers\Url;

$this->params['seo_title'] = $model->lang_seo_title;
$this->params['seo_description'] = $model->lang_seo_description;
$this->params['seo_keywords'] = $model->lang_seo_keywords;
$this->params['name'] = $model->lang_name;

$mainPage = Mainpage::findOne(1);

?>

<!--main-content-->
<div class="main-content">
    <section class="order-title-section">
        <?=$this->render('@frontend/views/blocks/bron')?>
        <div class="container">
            <ul class="breadcrumbs">
                <li><span><?=$model->lang_name?></span></li>
            </ul>
            <h1><?=(!empty($model->lang_seo_h1)) ? $model->lang_seo_h1 : $model->lang_name?></h1>
            <div class="year-price">
                <?=$model->lang_anons?>
            </div>
        </div>
    </section>

    <!-- =============== ТАБЛИЦА ИНФОРМАЦИИ =================== -->
    <section class="info-table-section">
        <div class="container info-container">
            <div class="info-table-outer">
                <?=$model->lang_table?>
            </div>
        </div>
        <div class="container">
            <div class="dop-info">
                <p><?=Yii::t('translate', 'extraCost')?> - 500 <?=Yii::t('translate', 'rubs')?>.</p>
                <p><?=Yii::t('translate', 'checkout time')?> - 12.00</p>
            </div>
        </div>
    </section>

    <!-- =================== ОБ ОТЕЛЕ ======================= -->
    <?=$mainPage->lang_about?>
</div>
<!--//main-content-->